services:
  demo-echo:
    build:  
      context: ./demo_echo
    #entrypoint:  ['/bin/sh','-c', "while true; do sleep 1; done;"]
    volumes:
      - ./config/fluent-bit-custom.conf:/etc/fluent-bit/fluent-bit-custom.conf
      - ./config/fluent-bit-parsers-custom.conf:/etc/fluent-bit/fluent-bit-parsers-custom.conf
    ports:
      - 8080:3000    
      - 5678:5678

  grafana-loki:
    image: grafana/loki
    ports:    
      - 3100:3100      
    volumes:
      - loki-storage:/loki

  grafana:
    image: grafana/grafana          
    ports:    
      - 3000:3000      
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana


volumes:
  loki-storage:
  grafana-storage: 

