apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://grafana-loki:3100
    basicAuth: false    
    editable: true
    version: 1
    jsonData:
      maxLines: 1000
          